### DISCUSSION TITLE
connect to postgis docker-container

### DISCUSSION THREAD

**Discussion by FabianRechsteiner** [developmentseed/tipg#146] [Q&A] [answered]
I use a docker-compose.yml File to manage different Vector-Tiles-Server in seperate containers..

1. container: postgis
2. container: tipg

Here the docker-compose.yml part for tipg:

```
  tipg:
    image: ghcr.io/developmentseed/tipg:latest
    container_name: tipg
    environment:
      #- DATABASE_URL=postgresql://${POSTGRES_USER_USERNAME:-tileserver}:${POSTGRES_USER_PASSWORD:-user_password}@postgis/${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER_USERNAME:-tileserver}
      - POSTGRES_PASS=${POSTGRES_USER_PASSWORD:-user_password}
      - POSTGRES_DBNAME=${POSTGRES_DB:-postgres}
      - POSTGRES_HOST=postgis
      - POSTGRES_PORT=5432
    volumes:
      - ./tipg:/config
    depends_on:
      - postgis
    profiles: ["tipg"]
    ports:
      - 8080:8080
```

> The variables are saved in an .env File.

With `docker compose --profile tipg up` i start my postgis-DB and tipg.
Both container are running, but i can't connect to http://localhost:8080/.

What is wrong? 

Do I need the [config File?]( https://github.com/developmentseed/tipg/blob/main/.env.example)

Thanks for your help

**Comment by vincentsarago** [comment]
@FabianRechsteiner you need to pass `PORT=8080` in the `tipg` block 

https://github.com/developmentseed/tipg/blob/main/docker-compose.yml#L9-L10

**Reply by FabianRechsteiner** [reply]
Thank you, that was the solution:

```
  tipg:
    image: ghcr.io/developmentseed/tipg:latest
    container_name: tipg
    environment:
      #- DATABASE_URL=postgresql://${POSTGRES_USER_USERNAME:-tileserver}:${POSTGRES_USER_PASSWORD:-user_password}@postgis/${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER_USERNAME:-tileserver}
      - POSTGRES_PASS=${POSTGRES_USER_PASSWORD:-user_password}
      - POSTGRES_DBNAME=${POSTGRES_DB:-postgres}
      - POSTGRES_HOST=postgis
      - POSTGRES_PORT=5432
      - PORT=8080
      ### TIPG-Parameters: https://developmentseed.org/tipg/user_guide/configuration/
      ### This Paramaters can also be safed in a seperate .env-File
      - TIPG_NAME="Welcome to my OGC Features and Tiles API"
      - TIPG_DB_SCHEMAS=["avprodukt", "public"]
      - TIPG_TABLE_CONFIG__pgstac_items__PK=objectid
    volumes:
     # - ./tipg:/config
      - ./tipg:/tmp/scripts
    depends_on:
      - postgis
    profiles: ["tipg"]
    ports:
      - 8080:8080
```
I created also some environment-parameters in my yml-File.
But i had to use `TIPG_DB_SCHEMAS=["avprodukt", "public"]` instead of `TIPG_DB_SCHEMAS='["myschema", "public"]'` from the [documentation](https://developmentseed.org/tipg/user_guide/configuration/)

I'm also not sure if the volumes are correct:
```
    volumes:
     # - ./tipg:/config
      - ./tipg:/tmp/scripts
```
I created a new File .env in my tipg-folder:
```
TIPG_NAME="OGC Features and Tiles API Test"
TIPG_DB_SCHEMAS=["avprodukt", "public"]
TIPG_TABLE_CONFIG__pgstac_items__PK=objectid
```
But the parameters could not be interpreted.
Where do i have to safe my .env - File?

Thank you for your help
